import { MigrationInterface, QueryRunner } from "typeorm";

export class AddIdempotencyKey1783112038845 implements MigrationInterface {
    name = 'AddIdempotencyKey1783112038845'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP CONSTRAINT "FK_6d272234992f11df68cc1e74d99"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "outstandingBalance"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "amountReceived"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "dueDate"`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "database" = $3 AND "schema" = $4 AND "table" = $5`, ["GENERATED_COLUMN","outstandingBalance","neondb","public","payment_expectations"]);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "customerId"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "expectationId"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "paidAt"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP CONSTRAINT "UQ_925e7ce5ff98df88b27ce488fda"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "nombaTransactionId"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "accountNumber"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP CONSTRAINT "UQ_d412d566e5a9dbf0101934ac8c7"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "nombaTransactionId"`);
        await queryRunner.query(`ALTER TABLE "disbursement_recipients" ADD "idempotencyKey" uuid`);
        await queryRunner.query(`ALTER TABLE "disbursement_recipients" ADD CONSTRAINT "UQ_6cc0cdc493bec6db0ee4f66c686" UNIQUE ("idempotencyKey")`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "idempotencyKey" uuid`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "UQ_86238dd0ae2d79be941104a5842" UNIQUE ("idempotencyKey")`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "merchantId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "accountId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "amountPaid" bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "outstanding" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "settledAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "merchantId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "paymentExpectationId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "transactionId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "runningTotal" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "outstandingAfter" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "merchantId" uuid`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "accountId" uuid`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "senderAccountNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "narration" character varying`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "receivedOnAccountNumber" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "rawWebhookPayload" jsonb NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."misplaced_payments_reason_enum" AS ENUM('ACCOUNT_SUSPENDED', 'ACCOUNT_CLOSED', 'ACCOUNT_NOT_FOUND', 'NO_EXPECTATION_FOUND')`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "reason" "public"."misplaced_payments_reason_enum" NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."misplaced_payments_resolutionaction_enum" AS ENUM('REROUTED', 'REFUNDED', 'WRITTEN_OFF')`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "resolutionAction" "public"."misplaced_payments_resolutionaction_enum"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "resolutionNote" text`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "reroutedToAccountId" uuid`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "refundMerchantTxRef" character varying`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "receivedAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "expectedAmount"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "expectedAmount" bigint NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."payment_expectations_status_enum" RENAME TO "payment_expectations_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."payment_expectations_status_enum" AS ENUM('PENDING', 'PARTIAL', 'SETTLED')`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ALTER COLUMN "status" TYPE "public"."payment_expectations_status_enum" USING "status"::"text"::"public"."payment_expectations_status_enum"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."payment_expectations_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "amount"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "amount" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "amount"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "amount" bigint NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."misplaced_payments_status_enum" RENAME TO "misplaced_payments_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."misplaced_payments_status_enum" AS ENUM('PENDING', 'RESOLVED')`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ALTER COLUMN "status" TYPE "public"."misplaced_payments_status_enum" USING "status"::"text"::"public"."misplaced_payments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."misplaced_payments_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD CONSTRAINT "FK_720f94403c9447f53b661bf57b1" FOREIGN KEY ("accountId") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD CONSTRAINT "FK_f907e00a2b38fe49215f5c03e31" FOREIGN KEY ("paymentExpectationId") REFERENCES "payment_expectations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD CONSTRAINT "FK_f93947fe69cd6c78581f0704959" FOREIGN KEY ("transactionId") REFERENCES "transactions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD CONSTRAINT "FK_bb7f05b258227990ab43bb954ef" FOREIGN KEY ("accountId") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP CONSTRAINT "FK_bb7f05b258227990ab43bb954ef"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP CONSTRAINT "FK_f93947fe69cd6c78581f0704959"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP CONSTRAINT "FK_f907e00a2b38fe49215f5c03e31"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP CONSTRAINT "FK_720f94403c9447f53b661bf57b1"`);
        await queryRunner.query(`CREATE TYPE "public"."misplaced_payments_status_enum_old" AS ENUM('UNMATCHED', 'UNDER_REVIEW', 'HELD', 'RECOVERED', 'REFUNDED')`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ALTER COLUMN "status" TYPE "public"."misplaced_payments_status_enum_old" USING "status"::"text"::"public"."misplaced_payments_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ALTER COLUMN "status" SET DEFAULT 'UNMATCHED'`);
        await queryRunner.query(`DROP TYPE "public"."misplaced_payments_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."misplaced_payments_status_enum_old" RENAME TO "misplaced_payments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "amount"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "amount" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "amount"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "amount" integer NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."payment_expectations_status_enum_old" AS ENUM('PENDING', 'PARTIAL', 'COMPLETE', 'OVERPAID')`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ALTER COLUMN "status" TYPE "public"."payment_expectations_status_enum_old" USING "status"::"text"::"public"."payment_expectations_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."payment_expectations_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_expectations_status_enum_old" RENAME TO "payment_expectations_status_enum"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "expectedAmount"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "expectedAmount" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "receivedAt"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "refundMerchantTxRef"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "reroutedToAccountId"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "resolutionNote"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "resolutionAction"`);
        await queryRunner.query(`DROP TYPE "public"."misplaced_payments_resolutionaction_enum"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "reason"`);
        await queryRunner.query(`DROP TYPE "public"."misplaced_payments_reason_enum"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "rawWebhookPayload"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "receivedOnAccountNumber"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "narration"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "senderAccountNumber"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "accountId"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "merchantId"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "outstandingAfter"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "runningTotal"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "transactionId"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "paymentExpectationId"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "merchantId"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "settledAt"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "outstanding"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "amountPaid"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "accountId"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "merchantId"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "UQ_86238dd0ae2d79be941104a5842"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "idempotencyKey"`);
        await queryRunner.query(`ALTER TABLE "disbursement_recipients" DROP CONSTRAINT "UQ_6cc0cdc493bec6db0ee4f66c686"`);
        await queryRunner.query(`ALTER TABLE "disbursement_recipients" DROP COLUMN "idempotencyKey"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "nombaTransactionId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD CONSTRAINT "UQ_d412d566e5a9dbf0101934ac8c7" UNIQUE ("nombaTransactionId")`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "accountNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "nombaTransactionId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD CONSTRAINT "UQ_925e7ce5ff98df88b27ce488fda" UNIQUE ("nombaTransactionId")`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "paidAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "expectationId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "customerId" character varying NOT NULL`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES ($1, $2, $3, $4, $5, $6)`, ["neondb","public","payment_expectations","GENERATED_COLUMN","outstandingBalance","\"expectedAmount\" - \"amountReceived\""]);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "outstandingBalance" integer GENERATED ALWAYS AS ("expectedAmount" - "amountReceived") STORED`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "dueDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "amountReceived" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD CONSTRAINT "FK_6d272234992f11df68cc1e74d99" FOREIGN KEY ("expectationId") REFERENCES "payment_expectations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
