import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1783083368575 implements MigrationInterface {
    name = 'InitialSchema1783083368575'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP CONSTRAINT "FK_6d272234992f11df68cc1e74d99"`);
        await queryRunner.query(`CREATE TYPE "public"."merchants_status_enum" AS ENUM('ACTIVE', 'SUSPENDED')`);
        await queryRunner.query(`CREATE TABLE "merchants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "businessName" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying, "webhookUrl" character varying, "webhookSecret" character varying NOT NULL, "status" "public"."merchants_status_enum" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7682193bcf281285d0a459c4b1e" UNIQUE ("email"), CONSTRAINT "PK_4fd312ef25f8e05ad47bfe7ed25" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."accounts_kyctier_enum" AS ENUM('TIER_1', 'TIER_2', 'TIER_3')`);
        await queryRunner.query(`CREATE TYPE "public"."accounts_status_enum" AS ENUM('ACTIVE', 'SUSPENDED', 'CLOSED')`);
        await queryRunner.query(`CREATE TABLE "accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "merchantId" uuid NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying NOT NULL, "bvn" character varying, "nin" character varying, "kycTier" "public"."accounts_kyctier_enum" NOT NULL DEFAULT 'TIER_1', "nombaAccountRef" character varying NOT NULL, "nombaAccountNumber" character varying NOT NULL, "nombaBankName" character varying NOT NULL, "nombaAccountName" character varying NOT NULL, "nombaProvisioningResponse" jsonb, "status" "public"."accounts_status_enum" NOT NULL DEFAULT 'ACTIVE', "suspendedAt" TIMESTAMP, "closedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1507287be8a1ccfc6247e2205e0" UNIQUE ("nombaAccountRef"), CONSTRAINT "UQ_91f471be3afed6912692594a042" UNIQUE ("nombaAccountNumber"), CONSTRAINT "PK_5a7a02c20412299d198e097a8fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "merchantId" uuid NOT NULL, "entityType" character varying NOT NULL, "entityId" uuid NOT NULL, "action" character varying NOT NULL, "previousState" jsonb, "newState" jsonb NOT NULL, "triggeredBy" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."disbursement_recipients_status_enum" AS ENUM('PENDING', 'SUCCESS', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "disbursement_recipients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "merchantId" uuid NOT NULL, "disbursementId" uuid NOT NULL, "accountNumber" character varying NOT NULL, "bankCode" character varying NOT NULL, "accountName" character varying NOT NULL, "amount" bigint NOT NULL, "narration" character varying, "merchantTxRef" character varying NOT NULL, "nombaTxId" character varying, "nombaStatus" character varying, "nombaRawResponse" jsonb, "status" "public"."disbursement_recipients_status_enum" NOT NULL DEFAULT 'PENDING', "failureReason" text, "retryCount" integer NOT NULL DEFAULT '0', "lastRetriedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4a49bdbb0347dfe048ce6bf2bfd" UNIQUE ("merchantTxRef"), CONSTRAINT "PK_b9e5c03f54eec30d535b1ea8f22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."disbursements_status_enum" AS ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'PARTIALLY_FAILED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "disbursements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "merchantId" uuid NOT NULL, "reference" character varying NOT NULL, "narration" character varying, "totalAmount" bigint NOT NULL, "totalRecipients" integer NOT NULL, "totalSuccess" integer NOT NULL DEFAULT '0', "totalFailed" integer NOT NULL DEFAULT '0', "totalPending" integer NOT NULL DEFAULT '0', "status" "public"."disbursements_status_enum" NOT NULL DEFAULT 'PENDING', "completedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8b10d47072ef7d11c7dda147203" UNIQUE ("reference"), CONSTRAINT "PK_2f9ea0e5b8382113aaa3e51cdfa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."merchant_api_keys_status_enum" AS ENUM('ACTIVE', 'REVOKED')`);
        await queryRunner.query(`CREATE TABLE "merchant_api_keys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "merchantId" uuid NOT NULL, "keyHash" character varying NOT NULL, "keyPrefix" character varying NOT NULL, "label" character varying, "status" "public"."merchant_api_keys_status_enum" NOT NULL DEFAULT 'ACTIVE', "lastUsedAt" TIMESTAMP, "revokedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6722cbec154166c54193cd7fcbf" UNIQUE ("keyHash"), CONSTRAINT "PK_e83f71483989cc0ba1decdbbbb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_type_enum" AS ENUM('INBOUND', 'OUTBOUND')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_status_enum" AS ENUM('PENDING', 'SETTLED', 'PARTIAL', 'MISPLACED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "merchantId" uuid NOT NULL, "accountId" uuid, "merchantTxRef" character varying NOT NULL, "nombaTxId" character varying, "nombaRequestId" character varying, "amount" bigint NOT NULL, "currency" character varying NOT NULL DEFAULT 'NGN', "senderName" character varying, "senderBank" character varying, "senderAccountNumber" character varying, "narration" character varying, "type" "public"."transactions_type_enum" NOT NULL, "status" "public"."transactions_status_enum" NOT NULL DEFAULT 'PENDING', "rawWebhookPayload" jsonb, "paymentExpectationId" uuid, "settledAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ed20769680c3e95607cfd76bbfd" UNIQUE ("merchantTxRef"), CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_435cb133f45d483dc0e1f0c7a7" ON "transactions"  ("nombaRequestId") `);
        await queryRunner.query(`CREATE TABLE "webhook_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "merchantId" uuid, "requestId" character varying NOT NULL, "eventType" character varying NOT NULL, "rawPayload" jsonb NOT NULL, "signatureVerified" boolean NOT NULL DEFAULT false, "processed" boolean NOT NULL DEFAULT false, "processedAt" TIMESTAMP, "processingError" text, "receivedAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4cba37e6a0acb5e1fc49c34ebfd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b404cb8ee9f09beb1a3e67dbb6" ON "webhook_events"  ("requestId") `);
        await queryRunner.query(`CREATE TYPE "public"."outbound_webhooks_status_enum" AS ENUM('PENDING', 'DELIVERED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "outbound_webhooks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "merchantId" uuid NOT NULL, "eventType" character varying NOT NULL, "payload" jsonb NOT NULL, "url" character varying NOT NULL, "status" "public"."outbound_webhooks_status_enum" NOT NULL DEFAULT 'PENDING', "attempts" integer NOT NULL DEFAULT '0', "lastAttemptAt" TIMESTAMP, "nextRetryAt" TIMESTAMP, "deliveredAt" TIMESTAMP, "lastResponseCode" integer, "lastResponseBody" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5fcc183fd2e50c1f12ae8eb5ae7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."reconciliation_logs_status_enum" AS ENUM('CLEAN', 'FLAGGED')`);
        await queryRunner.query(`CREATE TABLE "reconciliation_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "merchantId" uuid NOT NULL, "ranAt" TIMESTAMP NOT NULL, "periodFrom" TIMESTAMP NOT NULL, "periodTo" TIMESTAMP NOT NULL, "totalFetchedFromNomba" integer NOT NULL DEFAULT '0', "totalReconciled" integer NOT NULL DEFAULT '0', "totalOrphans" integer NOT NULL DEFAULT '0', "totalDrift" integer NOT NULL DEFAULT '0', "totalMissing" integer NOT NULL DEFAULT '0', "orphans" jsonb, "drifts" jsonb, "missing" jsonb, "status" "public"."reconciliation_logs_status_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5e33c6b50d85a7e0c0200b9c356" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "customerId"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "outstandingBalance" CASCADE`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "database" = $3 AND "schema" = $4 AND "table" = $5`, ["GENERATED_COLUMN","outstandingBalance","neondb","public","payment_expectations"]);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "amountReceived"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "dueDate"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "expectationId"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP CONSTRAINT "UQ_925e7ce5ff98df88b27ce488fda"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "nombaTransactionId"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "paidAt"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP CONSTRAINT "UQ_d412d566e5a9dbf0101934ac8c7"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "nombaTransactionId"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "accountNumber"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "merchantId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "accountId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "amountPaid" bigint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "outstanding" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "installmentCount" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "settledAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "merchantId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "paymentExpectationId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "transactionId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "runningTotal" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "outstandingAfter" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "merchantId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "accountId" uuid`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "senderAccountNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "narration" character varying`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "receivedOnAccountNumber" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "rawWebhookPayload" jsonb NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."misplaced_payments_reason_enum" AS ENUM('ACCOUNT_SUSPENDED', 'ACCOUNT_CLOSED', 'NO_EXPECTATION_FOUND')`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "reason" "public"."misplaced_payments_reason_enum" NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."misplaced_payments_resolutionaction_enum" AS ENUM('REROUTED', 'REFUNDED', 'WRITTEN_OFF')`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "resolutionAction" "public"."misplaced_payments_resolutionaction_enum"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "resolutionNote" text`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "reroutedToAccountId" uuid`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "refundMerchantTxRef" character varying`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "receivedAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "expectedAmount"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "expectedAmount" bigint NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."payment_expectations_status_enum" RENAME TO "payment_expectations_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."payment_expectations_status_enum" AS ENUM('PENDING', 'PARTIAL', 'SETTLED')`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ALTER COLUMN "status" TYPE "public"."payment_expectations_status_enum" USING "status"::"text"::"public"."payment_expectations_status_enum"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."payment_expectations_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "amount"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "amount" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "amount"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "amount" bigint NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."misplaced_payments_status_enum" RENAME TO "misplaced_payments_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."misplaced_payments_status_enum" AS ENUM('PENDING', 'RESOLVED')`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ALTER COLUMN "status" TYPE "public"."misplaced_payments_status_enum" USING "status"::"text"::"public"."misplaced_payments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."misplaced_payments_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_3155014caca190af05b571efcb1" FOREIGN KEY ("merchantId") REFERENCES "merchants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "disbursement_recipients" ADD CONSTRAINT "FK_f70c58602c21502d8d508c1c886" FOREIGN KEY ("disbursementId") REFERENCES "disbursements"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merchant_api_keys" ADD CONSTRAINT "FK_3d69aa89acf97cf49dbd413b9c7" FOREIGN KEY ("merchantId") REFERENCES "merchants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_26d8aec71ae9efbe468043cd2b9" FOREIGN KEY ("accountId") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD CONSTRAINT "FK_720f94403c9447f53b661bf57b1" FOREIGN KEY ("accountId") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD CONSTRAINT "FK_f907e00a2b38fe49215f5c03e31" FOREIGN KEY ("paymentExpectationId") REFERENCES "payment_expectations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD CONSTRAINT "FK_f93947fe69cd6c78581f0704959" FOREIGN KEY ("transactionId") REFERENCES "transactions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD CONSTRAINT "FK_bb7f05b258227990ab43bb954ef" FOREIGN KEY ("accountId") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP CONSTRAINT "FK_bb7f05b258227990ab43bb954ef"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP CONSTRAINT "FK_f93947fe69cd6c78581f0704959"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP CONSTRAINT "FK_f907e00a2b38fe49215f5c03e31"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP CONSTRAINT "FK_720f94403c9447f53b661bf57b1"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_26d8aec71ae9efbe468043cd2b9"`);
        await queryRunner.query(`ALTER TABLE "merchant_api_keys" DROP CONSTRAINT "FK_3d69aa89acf97cf49dbd413b9c7"`);
        await queryRunner.query(`ALTER TABLE "disbursement_recipients" DROP CONSTRAINT "FK_f70c58602c21502d8d508c1c886"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_3155014caca190af05b571efcb1"`);
        await queryRunner.query(`CREATE TYPE "public"."misplaced_payments_status_enum_old" AS ENUM('UNMATCHED', 'UNDER_REVIEW', 'HELD', 'RECOVERED', 'REFUNDED')`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ALTER COLUMN "status" TYPE "public"."misplaced_payments_status_enum_old" USING "status"::"text"::"public"."misplaced_payments_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ALTER COLUMN "status" SET DEFAULT 'UNMATCHED'`);
        await queryRunner.query(`DROP TYPE "public"."misplaced_payments_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."misplaced_payments_status_enum_old" RENAME TO "misplaced_payments_status_enum"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "amount"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "amount" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "amount"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "amount" integer NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."payment_expectations_status_enum_old" AS ENUM('PENDING', 'PARTIAL', 'COMPLETE', 'OVERPAID')`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ALTER COLUMN "status" TYPE "public"."payment_expectations_status_enum_old" USING "status"::"text"::"public"."payment_expectations_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."payment_expectations_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."payment_expectations_status_enum_old" RENAME TO "payment_expectations_status_enum"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "expectedAmount"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "expectedAmount" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "receivedAt"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "refundMerchantTxRef"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "reroutedToAccountId"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "resolutionNote"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "resolutionAction"`);
        await queryRunner.query(`DROP TYPE "public"."misplaced_payments_resolutionaction_enum"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "reason"`);
        await queryRunner.query(`DROP TYPE "public"."misplaced_payments_reason_enum"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "rawWebhookPayload"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "receivedOnAccountNumber"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "narration"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "senderAccountNumber"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "accountId"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" DROP COLUMN "merchantId"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "outstandingAfter"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "runningTotal"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "transactionId"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "paymentExpectationId"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" DROP COLUMN "merchantId"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "settledAt"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "installmentCount"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "outstanding"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "amountPaid"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "accountId"`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" DROP COLUMN "merchantId"`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "accountNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "nombaTransactionId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD CONSTRAINT "UQ_d412d566e5a9dbf0101934ac8c7" UNIQUE ("nombaTransactionId")`);
        await queryRunner.query(`ALTER TABLE "misplaced_payments" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "paidAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "nombaTransactionId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD CONSTRAINT "UQ_925e7ce5ff98df88b27ce488fda" UNIQUE ("nombaTransactionId")`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "expectationId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "dueDate" TIMESTAMP`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES ($1, $2, $3, $4, $5, $6)`, ["neondb","public","payment_expectations","GENERATED_COLUMN","outstandingBalance","\"expectedAmount\" - \"amountReceived\""]);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "outstandingBalance" integer GENERATED ALWAYS AS ("expectedAmount" - "amountReceived") STORED`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "amountReceived" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_expectations" ADD "customerId" character varying NOT NULL`);
        await queryRunner.query(`DROP TABLE "reconciliation_logs"`);
        await queryRunner.query(`DROP TYPE "public"."reconciliation_logs_status_enum"`);
        await queryRunner.query(`DROP TABLE "outbound_webhooks"`);
        await queryRunner.query(`DROP TYPE "public"."outbound_webhooks_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b404cb8ee9f09beb1a3e67dbb6"`);
        await queryRunner.query(`DROP TABLE "webhook_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_435cb133f45d483dc0e1f0c7a7"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_type_enum"`);
        await queryRunner.query(`DROP TABLE "merchant_api_keys"`);
        await queryRunner.query(`DROP TYPE "public"."merchant_api_keys_status_enum"`);
        await queryRunner.query(`DROP TABLE "disbursements"`);
        await queryRunner.query(`DROP TYPE "public"."disbursements_status_enum"`);
        await queryRunner.query(`DROP TABLE "disbursement_recipients"`);
        await queryRunner.query(`DROP TYPE "public"."disbursement_recipients_status_enum"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "accounts"`);
        await queryRunner.query(`DROP TYPE "public"."accounts_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."accounts_kyctier_enum"`);
        await queryRunner.query(`DROP TABLE "merchants"`);
        await queryRunner.query(`DROP TYPE "public"."merchants_status_enum"`);
        await queryRunner.query(`ALTER TABLE "payment_installments" ADD CONSTRAINT "FK_6d272234992f11df68cc1e74d99" FOREIGN KEY ("expectationId") REFERENCES "payment_expectations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
